### ISSUE TITLE
Error:(199, 0) No such property: encoding for class: com.eriwen.gradle.js.tasks.CombineJsTask_Decorated

### ISSUE THREAD

**Issue by piterwu** [eriwen/gradle-js-plugin#114]
No such property: encoding for class: com.eriwen.gradle.js.tasks.CombineJsTask_Decorated
plugin version is "1.12.1"

**Comment by Scuilion** [comment]
What does you build file look like?

**Comment by peter010** [comment]
just look like the readme example ：
combineJs {
    encoding = "UTF-8"
    source = javascript.source.dev.js.files
    dest = file("${buildDir}/all.js")
}
decompile  com.eriwen.gradle.js.tasks.CombineJsTask in gradle-js-plugin-1.12.1.jar .
public class CombineJsTask extends SourceTask
  implements GroovyObject
{

  @OutputFile
  private Object dest;

  public CombineJsTask()
  {
    CombineJsTask this;
    CallSite[] arrayOfCallSite = $getCallSiteArray();
    MetaClass localMetaClass = $getStaticMetaClass();
    this.metaClass = localMetaClass;
  }
...
does not have  ‘@Input encoding = System.properties['file.encoding']’ property
Is there packing problem

**Comment by Scuilion** [comment]
I think your on to something. I decompiled and saw the same missing enconding parameter.
Issue #103 was merged Nov 7 and version 1.12.0 was published (according to bintray) at the end of the year. 
@eriwen, do you have any thoughts on this?

**Comment by sothmann** [comment]
I am facing the same problem. Any chance to get this fixed soon?

**Comment by DongpoAlex** [comment]
I am facing the same problem.

**Comment by piterwu** [comment]
Write your own task like:
task myCombineJs(type: org.gradle.api.tasks.SourceTask) {
    def encoding = 'UTF-8'
   source = javascript.source.dev.js.files
    def dest = file("${buildDir}/all.js")
    ant.concat(destfile: (dest as File).canonicalPath, fixlastline: 'yes', encoding: encoding) {
        source.files.each {
            logger.info("Adding to fileset: ${it}")
            fileset(file: it)
        }
    }
}
