### ISSUE TITLE
Does this support incremental builds?

### ISSUE THREAD

**Issue by mumrah** [eriwen/gradle-js-plugin#122]
Do the built-in tasks define the inputs and outputs such that Gradle will determine up-to-dateness correctly?

Reference: http://gradle.org/feature-spotlight-incremental-builds/

Thanks!

**Comment by eriwen** [comment]
We have automated tests that ensure this here: https://github.com/eriwen/gradle-js-plugin/blob/master/src/test/groovy/com/eriwen/gradle/js/JsPluginFunctionalTest.groovy

Please file a separate issue if you find scenarios where UP-TO-DATE checks are incorrect.
