### ISSUE TITLE
requireJS not working 

### ISSUE THREAD

**Issue by parthirecipes** [eriwen/gradle-js-plugin#125]
requireJs {
    source = javascript.source.dev.js.files
    dest = file("${buildDir}/portal-all.js") 
    requirejs.buildprofile = new File("WebRoot/portal_ux/jsbuild/build.js")

}

Above is my configuration, but when I run the "gradle requireJs" its always throwing an error :+1: 
Error: Error: Missing either a "name", "include" or "modules" option
:portal:requireJs FAILED

FAILURE: Build failed with an exception.

Any help would be appreciated.

Thanks,
Parthi

**Comment by eriwen** [comment]
Could you please provide the contents of `WebRoot/portal_ux/jsbuild/build.js`? Is it possible that the path is incorrect?

**Comment by eriwen** [comment]
I'm going to close this due to inactivity. Please reopen if you have new information.
