### ISSUE TITLE
 No enum constant com.google.javascript.jscomp.CompilationLevel.ADVANCED_OPTIMISATIONS

### ISSUE THREAD

**Issue by akisystems** [eriwen/gradle-js-plugin#132]
I get the aforementioned error when running with the following configuration:

```
javascript.source {
    dev {
        js {
            srcDir 'src/main/resources/static/js'
            include "*.js"
            exclude "*.min.js"
        }
    }
    prod {
        js {
            srcDir 'src/main/resources/static/js'
            include "*.min.js"
        }
    }
}

minifyJs {
    source = 'src/main/resources/static/js/blah.js'
    dest = "${buildDir}/resources/main/static/js/blah.js"
    closure {
        compilationLevel = 'ADVANCED_OPTIMISATIONS'
        warningLevel = 'QUIET'
    }
}
```

I'm using version 2.12.0 and I've also tried 2.14.1, but the error appears with with either. Please help!

**Comment by eriwen** [comment]
@akisystems According to the [Closure Compiler docs](https://developers.google.com/closure/compiler/docs/compilation_levels), `compilationLevel` should actually be `'ADVANCED_OPTIMIZATIONS'`.

Please confirm if that fixes your issue and I'll close this.

**Comment by akisystems** [comment]
*facepalm* How stupid of me! Thanks and sorry for wasting your time!
