### ISSUE TITLE
No such property: source for class: com.eriwen.gradle.js.JsHintExtension_Decorated

### ISSUE THREAD

**Issue by IvannaBabchanik** [eriwen/gradle-js-plugin#133]
HI! 
I'm trying to include jshint to project and got the error: 

No such property: source for class: com.eriwen.gradle.js.JsHintExtension_Decorated
My conf file:
```
buildscript {

    ext {
        springBootVersion = '1.3.3.RELEASE'
    }

    repositories {
        maven { url 'http://nexus/content/repositories/thirdparty/' }
        maven { url 'http://nexus/content/repositories/public/' }
        maven { url 'http://nexus/content/repositories/cura-releases/' }
        maven { url "https://plugins.gradle.org/m2/" }
    }

    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath "com.eriwen:gradle-js-plugin:2.14.1"
    }
}



apply from: '../version.gradle'

apply plugin: "com.eriwen.gradle.js"

javascript.source {
    dev {
        js {
            srcDir "admin/src/main/resources/static/js"
            include "**/*.js"
            exclude "admin/src/main/resources/static/js/lib"
        }
    }
}

jshint {
    tasks.jshint.source = javascript.source.dev.js.files
    tasks.jshint.dest = file("${buildDir}/jshint.out")
    tasks.jshint.reporter = 'checkstyle'
    jshint.options = [expr: "true", unused: "true"]
}
```

Can someone explain me what I do wrong?

**Comment by eriwen** [comment]
I'm afraid I can't reproduce the problem. I've created an [example project for this issue](https://github.com/eriwen/gradle-3-0-testing/tree/master/gradle-js-133). Here's [a build scan](https://scans.gradle.com/s/fpvrp4gm4ty3e) of `gradlew jshint` working.

Could you please tell me what version of Gradle you're using? Would you consider changing the example project in order to create a reproducible test case?

**Comment by IvannaBabchanik** [comment]
Hi Eriwen! Thanks for your response. I'm using gradle 2.10. The issue was in wrong puling including (on example of  maine page is missing same part of configaration). I copy configuration from your example and everything work fine. Thanks

**Comment by freshcodemonger** [comment]
Why do you have to declare the properties prefixed with tasks.jshint?

The documentation on the main page makes it look like you can just do 
jshint {
source = 
}
